jdk:
- oraclejdk8

env:
  global:
  - secure: K8SfH3yGtA52it8BmGqc+rPU3gpDLQYOi6dydFXn7oGE2eW2Doe7xMZrZQTuBIOHfE1zBfKTCItnm4xmPGsLAKDs33YMLc/8xSlwqk3EMTBUiRVv4dsbm4cR8yUG97bLiygy3bJQyZOFs+s86D/plU/jMuEvWBIeFh2tDMgT9EDa9Ekth9a85A6WVtkbZKegGEHkAAGNH+OlUOB4d0ISsF3rDKFyw8pywYAWVjrYqtXXRZcR3EM354uH/EdX8Kw4UM7fWwFZu6ASiuBZ+Xsnuhjvf1914tF9dfJLhTnb7yuY4LC1QMb8TwC1GAGVmQJKWrlbgq+zfkg2Kx2jpwhuUiPUVUBnaYFjccH6DR/mv3Nf8PvmZxstJlGoN8y6Tnj9H/ZPkDiTNBQoVg/GjI82Mq5Ppox4F6q773Kx9YEKwjT1FMoOZERbngwOJLCRvK8/eRdJOOBYF2Fv80vYxif1DcSyzNk8jZmAm3GNehYym2ofAADD6+egvGMYd0QFNjb143va0k72Q2mOox8qAhFiawuKcffbr6xCm8/24xjhVgsXctExxYioIp9uropKWewWcv2LZoXJ48zCnw6x1v6BBmEIiHbA8DajGsXPodr2CwYaK4DnqwPjoeLmElUAwzDJuL6bYdH8NVw5qDlHoHC11NHjePCTGIusNwoOJCvUKIo=
  - secure: UuWZBZslpj2DPnd4IXJKe3Pg0Ajx98CSY+b2WMi6Byr+e60avIX9u/B+7QdS4K0gOtScVg7y04AGvBoUwUNf3sN6BRqzMKS4M0UTmKAFI0T5gHVo2WBsYi+jac1qXFJU2jx7hcB9JhUUlWt0oCsuTNZUZo334sZq7x4+cQdeasNt1dW9Ca+Mmvkov+Ivhnrgfxlx2fQfPYFvN/RsxnOhw/ULzs5KGlS6LcYvvYbAJxekK8AMTDA8POSbHY+QuH4X/TX0bBVw5Ryun6GpjEA1Wq8f+JDt+R0hkaeTe29Gdl2TQmqvpIBKnML5sFxL+/B+2HcxiV+J+JsFUjRe0mjnLRq/OAST0N8cKLYb334Ffu3+lGHuZKLVuohkC0N6L3nuwNoRBTYyrLJkIcwPY3ao4o3P9pHeI4gzQV2DTaIWtZPwvexEQdH62+XR31rhePIoSbhwuG1o3MIc28AoMG5jEIdUhuxQ/u5HP/TnjOcL3sY1fdQbGYpZAHFBI7C5zrBYgz0YjOKEr3TwGnEGM4tktPmOwqYH71SwJLcHC9VsFFoR3Yvk+d2NUruvWFQOALDBqVa391+5iWUfHCaq5f6lM7aLyHW887kWKJtWgj0sglyMmXCAZr4YkhasOBq1I8hAeFCdBMjzaw2v5VDVL7WTAbGXyggRtJ1y6h61EIauPLg=

script:
- mvn clean install -f pom.xml

after_success:
- chmod +x ./.travis/artifact-delete.sh
- chmod +x ./.travis/artifact-upload.sh
- "./.travis/artifact-delete.sh"
- "./.travis/artifact-upload.sh"
